export class folioDetailModel
{
    SUBE_ADI;
    Adisyonno;
    masano;
    ACILIS_ZAMANI;
    KAPANIS_ZAMANI;
    URUN_YAZILMA_SAATI;
    KISI_SAYISI;
    ADISYON_NOTU;
    PERSONEL;
    OTURMA_SURESI;
    GARSONIYE;
    ADS_PERSONEL;
    tutar;
    ADISYON_TOPLAMI;
    urunadi;
    ADET;
    GELIR;
    SILINME_SEBEBI;
    IKRAM_NEDEN;
    IKRAM;
    Y_8_KDV_MATRAH;
    Y_18_KDV_MATRAH;
    Y_8_KDV;
    Y_18_KDV;
    INDIRIM_ORANI;
    ISKONTO_BUTONU;
    ISKONTO_NEDENI;
    INDIRIM;
}